db.url=jdbc:mysql://localhost:3306/Concurso_Restaurante_DB?serverTimezone=UTC
db.user=ramiro
db.password=Password123!
# Configuración de Mailtrap
mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.user=1c6f432458260d
mail.password=2c2610f1fb496f